# Generated by Django 3.2.9 on 2021-12-09 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_users_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.account'),
        ),
    ]
