# Generated by Django 3.2.9 on 2021-12-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_users_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='company_name',
        ),
        migrations.AddField(
            model_name='account',
            name='company_name',
            field=models.CharField(default='brototype', max_length=250),
        ),
    ]
