# Generated by Django 3.2.9 on 2021-12-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_auto_20211212_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='company_name',
            field=models.CharField(max_length=250),
        ),
    ]
