# Generated by Django 3.2.9 on 2021-12-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobile_number',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
