# Generated by Django 3.2.9 on 2021-12-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_alter_users_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('product_code', models.IntegerField()),
                ('price', models.FloatField()),
                ('tax', models.FloatField()),
                ('units', models.IntegerField()),
            ],
        ),
    ]
