# Generated by Django 3.2.9 on 2021-12-18 05:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_contactdetails_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=55), null=True, size=None),
        ),
        migrations.AddField(
            model_name='person',
            name='mobile_num',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='mobile_num',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
