# Generated by Django 3.2.9 on 2021-12-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_auto_20211218_0515'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contactdetails',
        ),
    ]
