# Generated by Django 3.2.9 on 2021-12-18 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_delete_contactdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
